export const API_KEY = 'cef58a8dbf344ddda5bfae95fe41f075';
export const API_TOKEN = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZWY1OGE4ZGJmMzQ0ZGRkYTViZmFlOTVmZTQxZjA3NSIsInN1YiI6IjYwOGM4ZDdkYzU4NDBkMDA3Nzk1NTczMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WuFdKQOTLl1fIYyey9HUVeK_BfNZGzSQeAST58TIjnI';
export const appStorageName ='movie-app-favs';
export const APP_FOLDER_NAME = 'moviena';